// Phonodeck: the curated experiences offered in the set-up. Add an object to PRESETS to add an experience.
// Plain scripts that share one global scope (no build step); index.html loads them in order: prompts, experiences, core, engine, voice, curator, ui.

// Curator's picks: ready-made stories. One tap fills the description, the feeling and every set-up answer (the description can be
// edited); "beats" go to the Game Master only, as a guide for a good series of events.
const PRESETS = [
  { id: 'paris', label: 'Paris, 1944: The Medic Comes Home', title: 'The Medic Comes Home',
    feeling: 'From numbness to seeing the beauty in everything again',
    describe: 'I am a field medic just back in Paris from the front, a week after the Liberation. The city is celebrating, but all I can see is rubble and ration queues. Then I meet people who see the world completely differently, and slowly they show me the beauty I stopped noticing.',
    world: 'Paris, late August 1944, the week after the Liberation',
    vibe: 'Melancholic, Wholesome, Cozy',
    who: 'A field medic in the Free French forces, home on leave after a year at the front: good hands, few words, sleeps badly',
    traits: 'Steady and kind in a crisis, but numb, guarded and certain the world has lost its colour',
    where: 'A café terrace in Montmartre on a hot, bright morning, church bells ringing, flags in every window, while I sit apart with a cup of bad chicory coffee',
    hook: 'Find a reason to feel alive again before my leave ends and I go back to the front',
    allies: 'Lucien, a one-armed accordion player who plays for anyone who looks sad; Madame Odette, a flower seller who grows roses in shell craters; Pipo, a seven-year-old who collects lost buttons and the stories behind them',
    threat: 'My own grief and exhaustion, the memory of the soldiers I could not save, and the day my leave runs out',
    play: 'Lots of dialogue, Rich, detailed prose, Forgiving',
    avoid: 'Keep it PG-13; no gore, the war stays mostly off-stage',
    beats: 'Open on the noise of celebration that the medic cannot feel. Each companion offers one small, concrete beauty (a song, a rose, a button with a story) and asks nothing in return. Midway, a medical emergency in the street lets the medic\'s skill save someone, and the city sees them. Plant Pipo\'s button collection early: at the end Pipo gives the medic a button "to remember Paris by", the one from their own uniform, found on the first morning. End at dusk with the city lights coming on for the first time in four years.' },
  { id: 'trek', label: 'Star Trek TNG: First Contact', title: 'First Contact',
    feeling: 'Wonder, pride, and laughing with my crew',
    describe: 'I am the captain of a brand-new starship on her maiden mission. My first officer is an android trying earnestly to understand humour, and my doctor is brilliant, jaded and very funny. A species has just made its first warp flight, and we must make first contact without frightening them, embarrassing the Federation, or letting the doctor say anything unfortunate.',
    world: 'Star Trek: The Next Generation era, 2369, aboard a brand-new Federation starship',
    vibe: 'Funny, Epic, Wholesome',
    who: 'The newly promoted captain of the USS Halcyon, on her maiden voyage: young for the chair and determined to get this right',
    traits: 'Diplomatic and quick-witted, but impatient and a little too eager to impress Starfleet Command',
    where: 'The bridge of the USS Halcyon, still smelling of new carpet, as the ship drops out of warp near the Teyari homeworld and their tiny first warp ship streaks past',
    hook: 'Make a first contact the Teyari will celebrate for a thousand years',
    allies: 'Commander Ithen, an android first officer studying humour with great seriousness and terrible timing; Dr. Margot Hale, the jaded, brilliant chief medical officer who has seen everything twice; Ensign Pell, a nervous young pilot',
    threat: 'A Teyari general convinced the aliens are invaders, a ship\'s computer still full of maiden-voyage bugs, and Starfleet Command watching every word',
    play: 'Lots of dialogue, Puzzles and clues, Forgiving',
    avoid: 'Keep it PG-13; gentle humour, true to the spirit of the show',
    beats: 'Start with the Teyari warp test going wrong: their pilot is stranded, and saving her means revealing the ship. Commander Ithen\'s attempts at jokes misfire early, then one lands perfectly at the most tense moment of the negotiation. Dr. Hale treats the Teyari pilot and becomes her unlikely friend. The general\'s fear peaks in a standoff that is won with honesty and a shared laugh, not phasers. End with the Teyari inviting the crew to their first warp festival, and Ithen\'s first genuine laugh.' },
  { id: 'venice', label: 'Venice, 1750: The Mask-Maker\'s Secret', title: 'The Mask-Maker\'s Secret',
    feeling: 'Mischief and delight',
    describe: 'I am a mask-maker in Venice on the first night of Carnival, and my little workshop is one unpaid rent away from closing. At midnight a nervous stranger in a silver mask offers me a fortune to make him a disguise so ordinary that nobody looks at him twice, and then to show him Carnival until dawn without anyone recognising him. Someone important is searching the city for him, and I want to know who he really is.',
    world: 'Venice, February 1750, the first night of Carnival',
    vibe: 'Whimsical, Mysterious, Funny',
    who: 'A mask-maker with a tiny, crooked workshop by the Rialto Bridge, famous for masks so good that people swear they change your face, and behind on the rent',
    traits: 'Clever with my hands and my tongue, but nosy, a little vain, and terrible at keeping secrets',
    where: 'My workshop by the Rialto Bridge at midnight: one candlelit room over the Grand Canal, masks drying on every wall and the bells ringing in Carnival, just as a stranger in a silver mask knocks at my door',
    hook: 'Earn the stranger\'s fortune and save my workshop by keeping him unrecognised until dawn, and work out who he really is',
    allies: 'Bettina, my sharp-eyed apprentice who notices everything and asks too many questions; Ombra, a black cat who belongs to no one and turns up wherever trouble is about to happen',
    threat: 'Signor Zorzi, the palace\'s fussy, relentless chief steward, who is quietly searching every mask shop and every crowd in Venice for someone who has gone missing; and dawn, when every mask comes off',
    play: 'Lots of dialogue, Puzzles and clues, Exploration',
    avoid: 'Keep it PG-13; playful, not dark',
    beats: 'Open with the player alone in the workshop and the stranger at the door, and nobody else (a black cat may watch from a beam, unnamed until someone says her name). The stranger pays in gold ducats two hundred years old and talks like a man used to being obeyed but not to opening his own doors. Making his disguise is the first fun puzzle: what makes a face ordinary? Bettina arrives only after the deal is struck, back from an errand, and spots something odd about the stranger at once. Then out into Carnival for small, funny scrapes as the stranger tries to be ordinary (he has never queued, haggled or paid for anything himself). Signor Zorzi appears around the middle, searching the crowd, and the player has to fool him to his face. Clues add up to the truth: the stranger is the old Doge himself, longing to be an ordinary man for one night. End at dawn on a bridge as the masks come off, Zorzi arriving a moment too late, and the Doge\'s gratitude saving the workshop.' },
  { id: 'hollywood', label: 'Hollywood, 1927: The Last Silent Picture', title: 'The Last Silent Picture',
    feeling: 'Giddy fun and a big finish',
    describe: 'I am the most famous face in silent pictures, and I have never once spoken on screen. The talkies are coming, and the studio\'s nervous young sound engineer has one week to make me sound like a star. My rival wants me to flop, my producer is selling the studio to a pickle magnate, and the premiere is Friday.',
    world: 'Hollywood, October 1927, the week The Jazz Singer changes everything',
    vibe: 'Funny, Whimsical, Epic',
    who: 'The biggest star of silent pictures, adored for my eyebrows and my pratfalls, terrified of my own voice',
    traits: 'Charming, fearless at stunts and a born ham, but vain, dramatic and secretly convinced I sound like a goose',
    where: 'A sound stage at Paragon Pictures, padded with blankets against noise, a microphone hidden in a flower pot, five days before the premiere',
    hook: 'Survive the switch to talking pictures and make Friday\'s premiere the triumph of the decade',
    allies: 'Eddie Marsh, the jittery young sound engineer who is secretly a genius; Gloria Fenn, my wisecracking stunt double; Mr. Abernathy, my long-suffering butler who has heard me sing in the bath',
    threat: 'Vivienne LaRue, my glamorous rival, who is sabotaging the sound tests; Horace Gherkin, the pickle magnate buying the studio; and the ticking clock to Friday',
    play: 'Lots of dialogue, Action heavy, Forgiving',
    avoid: 'Keep it PG-13; slapstick welcome',
    beats: 'The first sound test is a disaster in a funny way (the microphone picks up everything except the star). Vivienne\'s sabotage escalates with each day. Eddie\'s invention keeps nearly working. Plant Mr. Abernathy\'s remark about the bath singing early: at the premiere the sound fails and the star saves the night by singing live, a voice nobody expected. Mr. Gherkin, charmed, keeps the studio. End with a standing ovation and a cue for a sequel.' },
  { id: 'orient', label: 'Orient Express, 1931: The Magician\'s Last Trick', title: 'The Magician\'s Last Trick',
    feeling: 'Cosy delight with a puzzle',
    describe: 'I am a travelling stage magician on the Orient Express from Paris to Istanbul. On the first night a duchess\'s diamond vanishes in the middle of my act. Everyone assumes it is part of the show, including me, until I realise I did not do it. I have three snowbound days and a carriage of eccentric suspects to find out who did.',
    world: 'The Orient Express, winter 1931, snowbound in the Balkan mountains',
    vibe: 'Cozy, Mysterious, Funny',
    who: 'The Great Marvello, a travelling stage magician: sleight of hand, a velvet cape and a carefully hidden past as a pickpocket',
    traits: 'Quick hands and a quicker eye for a lie, but a show-off who cannot resist an audience',
    where: 'The gleaming dining car of the Orient Express at midnight, chandeliers swaying, snow piling against the windows as the train grinds to a halt in a mountain pass',
    hook: 'Find the Duchess\'s stolen diamond, the Star of Odessa, before the train reaches Istanbul and the police arrest the obvious suspect: me',
    allies: 'Pip, my teenage assistant who is braver than me; Inspector Kova, a sleepy Yugoslav policeman who is much sharper than he looks; Duchess Anastasia, who seems strangely unbothered by her loss',
    threat: 'A thief hidden among the passengers (a nervous honeymooning couple, a famous novelist, a chess grandmaster and a very polite conductor), and my own past catching up with me',
    play: 'Puzzles and clues, Lots of dialogue, Forgiving',
    avoid: 'Keep it PG-13; no murder, a cosy mystery',
    beats: 'The theft happens during the magician\'s vanishing trick, so every clue is hidden in the act itself. Each suspect has a harmless secret that looks guilty. The novelist is secretly writing the whole thing down. Plant the Duchess\'s calm early: she hid the diamond herself to test who on the train could be trusted, but a real thief then took it from her hiding place. The magician solves it with one last trick in the dining car. End with the train pulling into Istanbul at sunrise.' },
  { id: 'moon', label: 'The Moon, 2069: The First Café on the Moon', title: 'The First Café on the Moon',
    feeling: 'Warm, cosy wonder',
    describe: 'I have just opened the first café on the Moon, in a dome looking out at the Earth. My regulars are a homesick astronaut, a robot who wants to learn to bake, and a billionaire who keeps trying to buy the place. Tonight the Earth will be full in the sky, and someone very important has booked a table.',
    world: 'Tranquility Base, the Moon, 2069, a hundred years after the first landing',
    vibe: 'Cozy, Whimsical, Wholesome',
    who: 'The owner of Earthrise, the first café on the Moon: a former engineer who gave up rockets to make the perfect cup of coffee in one-sixth gravity',
    traits: 'Warm, inventive and a brilliant fixer of broken things, but stubborn and hopeless with money',
    where: 'Earthrise café, a glass dome on the rim of a crater, the blue Earth hanging in the black sky, coffee steam rising very slowly in low gravity',
    hook: 'Make tonight perfect for the mysterious guest who booked the best table for Full Earth night, and keep the café out of the billionaire\'s hands',
    allies: 'Commander Asha Reyes, a homesick astronaut who has not been home in two years; BX-7, a maintenance robot determined to bake bread; Lemon, the café\'s very confused cat',
    threat: 'Silas Crane, a charming billionaire who wants to turn the café into a theme park; a failing air recycler; and dough that will not rise in low gravity',
    play: 'Lots of dialogue, Exploration, Forgiving',
    avoid: 'Keep it PG; cosy, no peril beyond a few malfunctions',
    beats: 'Every regular has a small wish for the evening. BX-7\'s bread keeps floating away, a running gag that pays off. The air recycler fails at the worst moment and the owner fixes it with something from the kitchen. Plant the reserved table early: the important guest turns out to be the last surviving person who watched the 1969 landing on television as a child, here to see the Earth from the Moon at last. Silas Crane is moved and backs off. End with everyone watching the full Earth together.' }
];
