// Phonodeck: the curated experiences offered in the set-up. Add an object to PRESETS to add an experience.
// Plain scripts that share one global scope (no build step); index.html loads them in order: prompts, experiences, core, engine, voice, curator, ui.

// Curator's picks: ready-made stories, plus experiences marked sim: true (the experience simulator: no plot, and "goal" is the player's
// goal). One tap fills the description, the feeling and every set-up answer (the description can be edited); "beats" go to the Game
// Master only, as a guide for a good series of events.
const PRESETS = [
  { id: 'speakeasy', sim: true, label: 'Los Angeles, 1925: A Speakeasy in the Rain', title: 'A Speakeasy in the Rain',
    feeling: 'Warm, nostalgic comfort',
    describe: 'It is a stormy night in Los Angeles in 1925, and I have ducked into a hidden speakeasy to wait out the rain. I take a stool at the bar and talk with the serious, quiet bartender and a friendly regular about their hopes and dreams for the future.',
    world: 'Los Angeles, 1925, during Prohibition',
    vibe: 'Cozy, Melancholic, Wholesome',
    who: 'A traveller new in town, soaked from the storm, with time to kill and a good ear for other people\'s stories',
    traits: 'Curious and easy to talk to, but a little homesick',
    where: 'A small speakeasy hidden behind a flower shop downtown: rain drumming on the skylight, a jazz record crackling on the gramophone, a warm lamp over a long mahogany bar',
    goal: 'Sit at the bar, wait out the storm, and hear the bartender and the regular talk about their hopes and dreams for the future',
    allies: 'Walter Pruitt, the bartender: serious, precise and quietly kind, saving every nickel for a dream he rarely mentions; Dolores Vega, a regular who sews costumes for the movie studios and is sure her big break is just around the corner',
    play: 'Lots of dialogue, Forgiving',
    avoid: 'Keep it PG-13; no danger and no police raid, just warm conversation' },
  { id: 'suwarrow', sim: true, label: 'Suwarrow, Cook Islands: Washed Ashore', title: 'Washed Ashore',
    feeling: 'Deep connection and friendship',
    describe: 'My cruise ship has sunk, and I have washed up on Suwarrow, a tiny coral atoll in the Cook Islands, hundreds of miles from anywhere. There is no danger and no race to be rescued. On the island I meet a stranger, and slowly we become good friends.',
    world: 'Suwarrow atoll, the Cook Islands, today',
    vibe: 'Wholesome, Cozy, Whimsical',
    who: 'A cruise passenger who has just washed ashore with nothing but the clothes I am wearing and a waterproof watch',
    traits: 'Resourceful and good-humoured, but used to being busy and not sure what to do with stillness',
    where: 'A white coral beach on Suwarrow at sunrise, a calm turquoise lagoon, coconut palms leaning over the water, and a line of footprints in the sand that are not mine',
    goal: 'Meet the stranger on the island, get to know them, and become good friends',
    allies: 'Teina, the stranger on the island: the soft-spoken caretaker of the atoll, who has lived here alone for years and knows every tide, reef and star',
    play: 'Lots of dialogue, Exploration, Forgiving',
    avoid: 'Keep it PG; no danger, no injuries and no rescue drama' },
  { id: 'trek', label: 'Star Trek TNG: First Contact', title: 'First Contact',
    feeling: 'Wonder, pride, and laughing with my crew',
    describe: 'I am the captain of a brand-new starship on her maiden mission. My first officer is an android trying earnestly to understand humour, and my doctor is brilliant, jaded and very funny. A species has just made its first warp flight, and we must make first contact without frightening them, embarrassing the Federation, or letting the doctor say anything unfortunate.',
    world: 'Star Trek: The Next Generation era, 2369, aboard a brand-new Federation starship',
    vibe: 'Funny, Epic, Wholesome',
    who: 'The newly promoted captain of the USS Halcyon, on her maiden voyage: young for the chair and determined to get this right',
    traits: 'Diplomatic and quick-witted, but impatient and a little too eager to impress Starfleet Command',
    where: 'The bridge of the USS Halcyon, still smelling of new carpet, as the ship drops out of warp near the Teyari homeworld and their tiny first warp ship streaks past',
    hook: 'Make a first contact the Teyari will celebrate for a thousand years',
    allies: 'Commander Ithen, an android first officer studying humour with great seriousness and terrible timing; Dr. Margot Hale, the jaded, brilliant chief medical officer who has seen everything twice; Ensign Pell, a nervous young pilot',
    threat: 'A Teyari general convinced the aliens are invaders, a ship\'s computer still full of maiden-voyage bugs, and Starfleet Command watching every word',
    play: 'Lots of dialogue, Puzzles and clues, Forgiving',
    avoid: 'Keep it PG-13; gentle humour, true to the spirit of the show',
    beats: 'Start with the Teyari warp test going wrong: their pilot is stranded, and saving her means revealing the ship. Commander Ithen\'s attempts at jokes misfire early, then one lands perfectly at the most tense moment of the negotiation. Dr. Hale treats the Teyari pilot and becomes her unlikely friend. The general\'s fear peaks in a standoff that is won with honesty and a shared laugh, not phasers. End with the Teyari inviting the crew to their first warp festival, and Ithen\'s first genuine laugh.' },
  { id: 'orient', label: 'Orient Express, 1931: The Magician\'s Last Trick', title: 'The Magician\'s Last Trick',
    feeling: 'Cosy delight with a puzzle',
    describe: 'I am a travelling stage magician on the Orient Express from Paris to Istanbul. On the first night a duchess\'s diamond vanishes in the middle of my act. Everyone assumes it is part of the show, including me, until I realise I did not do it. I have three snowbound days and a carriage of eccentric suspects to find out who did.',
    world: 'The Orient Express, winter 1931, snowbound in the Balkan mountains',
    vibe: 'Cozy, Mysterious, Funny',
    who: 'The Great Marvello, a travelling stage magician: sleight of hand, a velvet cape and a carefully hidden past as a pickpocket',
    traits: 'Quick hands and a quicker eye for a lie, but a show-off who cannot resist an audience',
    where: 'The gleaming dining car of the Orient Express at midnight, chandeliers swaying, snow piling against the windows as the train grinds to a halt in a mountain pass',
    hook: 'Find the Duchess\'s stolen diamond, the Star of Odessa, before the train reaches Istanbul and the police arrest the obvious suspect: me',
    allies: 'Pip, my teenage assistant who is braver than me; Inspector Kova, a sleepy Yugoslav policeman who is much sharper than he looks; Duchess Anastasia, who seems strangely unbothered by her loss',
    threat: 'A thief hidden among the passengers (a nervous honeymooning couple, a famous novelist, a chess grandmaster and a very polite conductor), and my own past catching up with me',
    play: 'Puzzles and clues, Lots of dialogue, Forgiving',
    avoid: 'Keep it PG-13; no murder, a cosy mystery',
    beats: 'The theft happens during the magician\'s vanishing trick, so every clue is hidden in the act itself. Each suspect has a harmless secret that looks guilty. The novelist is secretly writing the whole thing down. Plant the Duchess\'s calm early: she hid the diamond herself to test who on the train could be trusted, but a real thief then took it from her hiding place. The magician solves it with one last trick in the dining car. End with the train pulling into Istanbul at sunrise.' }
];
